---
- name: create deploy folder
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: 0755

- name: Copy artifact
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: Unpack artifact
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: Start backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start